services:
  php81:
    container_name: php81
    image: digiserv/php8-cli:8.1.20-alpine
    environment:
      COMPOSER_ROOT_VERSION: "6"
    volumes:
      - ./:/opt/project
    entrypoint: /bin/sh
    tty: true

  php82:
    container_name: php82
    image: digiserv/php8-cli:8.2.12-bookworm
    environment:
      COMPOSER_ROOT_VERSION: "6"
    volumes:
      - ./:/opt/project
    entrypoint: /bin/bash
    tty: true

  php83:
    container_name: php83
    image: digiserv/php8-cli:8.3.12-bookworm
    environment:
      COMPOSER_ROOT_VERSION: "6"
    volumes:
      - ./:/opt/project
    entrypoint: /bin/bash
    tty: true

  php84:
    container_name: php84
    image: digiserv/php8-cli:8.4.3-bookworm
    environment:
      COMPOSER_ROOT_VERSION: "7"
    volumes:
      - ./:/opt/project
    entrypoint: /bin/bash
    tty: true

